[package]
name = "glslopt"
version = "0.1.0"
authors = ["Jamie Nicol <jnicol@mozilla.com>"]
edition = "2018"
license = "MIT"

[build-dependencies]
bindgen = { version = "0.53", default-features = false, features = ["runtime"] } # disable `logging` to reduce code size
cc = "1.0"
